#config file used when running bacpipe to generate embeddings

#################### CONFIGURATION FILE ####################
# This file contains the configuration for the audio data path,
# the embedding model, and the dimensionality reduction model.
#
# The embedding model must be a list either of one or multiple models.
# 
# The dimensionality reduction model must be just one of the supported models.


# PATHS:
# define paths for your audio data
### IMPORTANT! WINODWS USERS DON'T USE QUOTATIONS HERE
audio_dir : '[path to recordings]'

#####################    PROCESS SETTINGS    ##############################

# specify if you want to overwrite the existing evaluation results
# this is useful if you want to re-run the evaluation with different parameters
overwrite: True


# specify if you want to visualize the embedding evaluations
dashboard: False

#########################################################################
####################    SELECT MODELS    ################################
#########################################################################

# embedding model name
models: [
      "perch_v2"
  ]

  # if already_computed is True, the embeddings will be loaded from the
  # embeddings directory in the dataset path in `results/by_dataset/`

  # if already_computed is False, the embeddings will be computed 
  # for all selected models

already_computed: False

#########################################################################
############    SELECT DIMENSIONALITY REDUCTION MODELS    ###############
#########################################################################

dim_reduction_model: "umap"



#########################################################################
#################    SELECT EVALUATION MEASURE    #######################
#########################################################################

evaluation_task: [
   "clustering",
   #"classification"
]

#########################################################################
######################### CLUSTERING TASK ###############################
#########################################################################

clustering:
 # method: kmeans
 # features: ["mfcc", "spectral_centroid", "zero_crossing_rate"]
 ## min_cluster_size: 5
 ## min_samples: 2
 ## metric: euclidean
 ## allow_single_cluster: True
 ## cluster_selection_epsilon: 0.0
 ## cluster_selection_method: eom
 # n_clusters: 10

  bool: False
  method: hdbscan
  features: ["mfcc", "spectral_centroid", "zero_crossing_rate"]
  min_cluster_size: 10
  min_samples: 5
  metric: euclidean


#########################################################################
######################### CLASSIFICATION TASK ###########################
#########################################################################
#THIS PART IS THE OLD ONE, BELOW ADDED
#classification:
#  method: random_forest
#  features: ["mfcc", "spectral_centroid", "zero_crossing_rate"]
#  labels: "species"

#########################################################################
######################### CLASSIFICATION TASK ###########################
#########################################################################

#classification:
  # model wrapper options
  #problem_type: multilabel        # new: "multilabel" vs "multiclass"
  #method: random_forest
  #wrapper: one_vs_rest            # options: one_vs_rest, multioutput
  #predict_proba: True

  # features & labels
  #features: ["mfcc", "spectral_centroid", "zero_crossing_rate"]
  #labels: "species"

  # scoring & output control
  #classifier_threshold: 0.1       # keep any class with score >= this
#  top_k: 5                        # optional: keep the top 5 per segment
  #multi_label_output: True        # ensure output writer writes multiple rows
